apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: finance-service-pdb
  namespace: finance
  labels:
    app: finance-service
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: finance-service
